package com.devteam.aiauditserver.services.project;


import com.devteam.aiauditserver.models.User.User;
import com.devteam.aiauditserver.services.utils.MailServiceUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class MailsSenderService {

    @Autowired
    private MailServiceUtil mailServiceUtil;

    public void sendAuditorWelcomeEmail(String subject, String to, User user, String passwd) {

        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder can be re-enabled here if needed
                .append("    </div>")
                .append("    <h2 style='color: #31317A; text-align: center;'>Welcome to Compliance Engine Platform</h2>")
                .append("    <p>Hello <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>Your Auditor account has been successfully created by the administrator. You can now access the platform using the credentials below:</p>")
                .append("    <div style='background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;'>")
                .append("      <p style='margin: 5px 0;'><strong>Email:</strong> ").append(user.getEmail()).append("</p>")
                .append("      <p style='margin: 5px 0;'><strong>Temporary Password:</strong> <span style='color: #7a3bfe; font-weight: bold;'>").append(passwd).append("</span></p>")
                .append("    </div>")
                .append("    <div style='text-align: center;'>")
                .append("      <a href='http://localhost:4200' style='background-color: #7a3bfe; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;'>Login to Platform</a>")
                .append("    </div>")
                .append("    <p style='font-size: 13px; color: #555; margin-top: 20px;'>As an Auditor, you will be responsible for conducting and reviewing system evaluations.</p>")
                .append("    <p style='font-size: 12px; color: #888; margin-top: 30px;'>Security Note: This password was auto-generated. For security purposes, please change it immediately after your first login.</p>")
                .append("  </div>")
                .append("</body></html>");

        // Trigger the async mail sender
        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }


    public void resendPassword(String subject, String to, User user, String passwd) {

        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder
                .append("    </div>")
                .append("    <h2 style='color: #31317A; text-align: center;'>Compliance Engine Platform</h2>")
                .append("    <p>Hi <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>A new password has been generated for your account. You can use the following credentials to access the platform:</p>")
                .append("    <div style='background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;'>")
                .append("      <p><strong>Email:</strong> ").append(user.getEmail()).append("</p>")
                .append("      <p><strong>New Temporary Password:</strong> <span style='color: #7a3bfe; font-weight: bold;'>").append(passwd).append("</span></p>")
                .append("    </div>")
                .append("    <div style='text-align: center;'>")
                .append("      <a href='http://localhost:4200' style='background-color: #7a3bfe; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;'>Go To Dashboard</a>")
                .append("    </div>")
                .append("    <p style='font-size: 12px; color: #888; margin-top: 30px;'>This password was automatically generated by the system. For security reasons, please ensure you change it immediately after logging in.</p>")
                .append("  </div>")
                .append("</body></html>");

        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }
    public void sendOtpEmail(String subject, String to, User user, String otp) {

        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder
                .append("    </div>")
                .append("    <h2 style='color: #31317A; text-align: center;'>Reset Your Password</h2>")
                .append("    <p>Hi <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>We received a request to reset the password for your account on the <strong>Compliance Engine Platform</strong>.</p>")
                .append("    <p>Please use the following One-Time Password (OTP) to proceed with the update:</p>")
                .append("    <div style='background: #f9f9f9; padding: 20px; border-radius: 5px; margin: 20px 0; text-align: center;'>")
                .append("      <span style='color: #7a3bfe; font-size: 32px; font-weight: bold; letter-spacing: 5px;'>").append(otp).append("</span>")
                .append("    </div>")
                .append("    <p style='font-size: 14px; color: #333;'>This code is valid for a limited time. If you did not request a password reset, please ignore this email or contact support if you have concerns.</p>")
                .append("    <div style='text-align: center; margin-top: 30px;'>")
                .append("      <p style='font-size: 12px; color: #888;'>This is an automated security notification. Please do not reply directly to this email.</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body></html>");

        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }

    public void sendWelcomePassword(String subject, String to, User user, String passwd) {

        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder
                .append("    </div>")
                .append("    <h2 style='color: #31317A; text-align: center;'>Welcome to Compliance Engine Platform!</h2>")
                .append("    <p>Hi <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>Thank you for signing up. Your account has been successfully created. You can now log in to the platform using the credentials below:</p>")
                .append("    <div style='background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;'>")
                .append("      <p style='margin: 5px 0;'><strong>Email:</strong> ").append(user.getEmail()).append("</p>")
                .append("      <p style='margin: 5px 0;'><strong>Generated Password:</strong> <span style='color: #7a3bfe; font-weight: bold;'>").append(passwd).append("</span></p>")
                .append("    </div>")
                .append("    <div style='text-align: center;'>")
                .append("      <a href='http://localhost:4200' style='background-color: #7a3bfe; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;'>Access My Dashboard</a>")
                .append("    </div>")
                .append("    <p style='font-size: 13px; color: #555; margin-top: 20px;'>We are thrilled to have you part of our auditing community.</p>")
                .append("    <p style='font-size: 12px; color: #888; margin-top: 30px;'>Important: For your security, please change this auto-generated password immediately after your first login in your profile settings.</p>")
                .append("  </div>")
                .append("</body></html>");

        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }

    public void sendDeactivationEmail(String subject, String to, User user) {

        // Use a StringBuilder for better performance with long HTML strings
        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder
                .append("    </div>")
                .append("    <h2 style='color: #D9534F; text-align: center;'>Account Deactivated</h2>") // Using a soft red for notice
                .append("    <p>Hello <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>This email is to inform you that your account on the <strong>Compliance Engine Platform</strong> has been deactivated by the system administrator.</p>")
                .append("    <div style='background: #fdf2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 5px solid #D9534F;'>")
                .append("      <p style='margin: 0; color: #333;'>Access to your dashboard, reports, and auditing tools is currently restricted.</p>")
                .append("    </div>")
                .append("    <p style='font-size: 14px; color: #555;'>If you believe this is a mistake or if you would like to request reactivation, please contact the platform administrator or your department head.</p>")
                .append("    <div style='text-align: center; margin-top: 30px;'>")
                .append("      <p style='font-size: 12px; color: #888;'>Security Reference ID: AUDIT-").append(user.getId()).append("</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body></html>");

        // Trigger the async mail sender
        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }
    public void sendActivationEmail(String subject, String to, User user) {

        // Use a StringBuilder for better performance with long HTML strings
        StringBuilder emailContent = new StringBuilder();
        emailContent.append("<!DOCTYPE html><html>")
                .append("<body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>")
                .append("  <div style='max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd;'>")
                .append("    <div style='text-align: center;'>")
                // Logo placeholder
                .append("    </div>")
                .append("    <h2 style='color: #28A745; text-align: center;'>Account Reactivated</h2>")
                .append("    <p>Hello <strong>").append(user.getName()).append("</strong>,</p>")
                .append("    <p>We are pleased to inform you that your account on the <strong>Compliance Engine Platform</strong> has been successfully reactivated.</p>")
                .append("    <div style='background: #f4faf4; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 5px solid #28A745;'>")
                .append("      <p style='margin: 0; color: #333;'>Your access to the dashboard, audit reports, and platform tools has been fully restored.</p>")
                .append("    </div>")
                .append("    <div style='text-align: center;'>")
                .append("      <a href='http://localhost:4200' style='background-color: #7a3bfe; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;'>Login to My Account</a>")
                .append("    </div>")
                .append("    <p style='font-size: 14px; color: #555; margin-top: 25px;'>You can now log in using your existing credentials. If you have forgotten your password, please use the \"Forgot Password\" option on the login page.</p>")
                .append("    <div style='text-align: center; margin-top: 30px;'>")
                .append("      <p style='font-size: 12px; color: #888;'>Thank you for being part of the Compliance Engine Platform community.</p>")
                .append("    </div>")
                .append("  </div>")
                .append("</body></html>");

        // Trigger the async mail sender
        mailServiceUtil.sendMail(to, subject, emailContent.toString(), true);
    }
}
